#Nombre de la version
version: "3.8"

services:
  mysql-db:
    image: mysql
    volumes:
      - ./datos:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin3
    ports:
      - ${DB_PORT_PHPMYADMIN}:80
    depends_on:
      - mysql-db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-db

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
